studio: studio user profile
ir-engine/ir-engine pull request #100
Opened 2024-08-28 16:51 UTC by achen5671

## Summary
https://tsu.atlassian.net/browse/IR-2520
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-09-03 18:02 UTC, barankyle requested changes

2024-09-03 18:02 UTC, barankyle commented on packages/editor/src/components/profile/Profile.tsx
> +  useEffect(() => {
I don't think we need anything that deals with oauthConnectedState in this file, since we're not displaying any of that information. Setting it to the initial state on logout on line 100 is also unnecessary for that reason.

2024-09-03 18:02 UTC, barankyle commented on packages/editor/src/components/profile/Profile.tsx
> +                type={showKeys.inviteCode.value ? 'text' : 'password'}
Did someone request that these fields be hidden by default and then toggleable? We don't hide the invite code or userId anywhere else.

2024-09-03 18:02 UTC, barankyle commented on packages/editor/src/components/profile/Profile.tsx
> +          <span className="text-md ml-4 flex cursor-pointer items-center gap-2 text-[#A0A1A2]">
This button doesn't do anything. I don't know if it's supposed to be here - my take would be to make users go to the dashboard to delete their account and not have a delete account button in the studio, but I'm not in charge of UX decisions. If it is supposed to be here, then it needs to do something, and I would imagine there should be a confirmation prompt so a stray click doesn't wipe your account.

2024-09-30 19:54 UTC, achen5671 commented
closing, replacing with a much simpler pr https://github.com/ir-engine/ir-engine/pull/347/files with new designs

2024-09-30 19:54 UTC, closed without merging