IR-4110: Fix tracking events
ir-engine/ir-engine pull request #109
Opened 2024-08-29 15:36 UTC by MoizAdnan

https://tsu.atlassian.net/browse/IR-4110

2024-09-16 10:45 UTC, aditya-mitra approved these changes
Looks good ✅

Are these logs sent to our servers?

2024-09-16 22:49 UTC, HexaField requested changes

2024-09-16 22:49 UTC, HexaField commented on packages/client-core/src/components/MediaIconsBox/index.tsx
> +              MediaStreamState.toggleWebcamPaused
need to call the function

2024-09-18 00:16 UTC, jonathan-casarrubias approved these changes

2024-09-18 00:17 UTC, jonathan-casarrubias commented
LGTM aside of the feedback already provided

2024-09-25 12:15 UTC, HexaField approved these changes

2024-09-26 07:58 UTC, hanzlamateen approved these changes

2024-09-26 07:58 UTC, merged