Model compression progress bar
ir-engine/ir-engine pull request #110
Opened 2024-08-29 17:23 UTC by Rezmason

## Summary
The model transform function now reports its progress, and the compression panel now has a captioned progress bar instead of a spinner.

## References
closes https://tsu.atlassian.net/browse/IR-4271

2024-08-29 23:28 UTC, dinomut1 requested changes, later dismissed
After running a default compression job on a file in "ir-props", the integrated prefab file is getting uploaded into /assets/assets/models rather than /assets/models
![image](https://github.com/user-attachments/assets/3b377d18-993d-44fe-ac4b-c4646b81fbdb)

2024-08-29 23:41 UTC, Rezmason commented
> After running a default compression job on a file in "ir-props", the integrated prefab file is getting uploaded into /assets/assets/models rather than /assets/models

![image](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdGp5dnd0MXV4N2FxNXlhcnczM3NkZTFrajB1NjQ0amZlaDlrOGg1bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/6JB4v4xPTAQFi/giphy.webp)

2024-08-30 04:00 UTC, aditya-mitra requested changes, later dismissed
few changes

2024-08-30 04:00 UTC, aditya-mitra commented on packages/editor/src/components/assets/ModelCompressionPanel.tsx
> +
in this case, the key value pairs are known. so an plain object would work here. we should utilise a map when we are dynamically adding or removing key values.

2024-08-30 04:00 UTC, aditya-mitra commented on packages/engine/src/assets/compression/ModelTransformFunctions.ts
> +    status
```suggestion
    _numerator,
    _denominator,
    _status
```

we can use `_` underscore to denote unused variable in this case

2024-08-30 16:46 UTC, Rezmason commented on packages/engine/src/assets/compression/ModelTransformFunctions.ts
> +    status
These are in a function declaration that's a default value for a function parameter, so I'll just delete the default value and make the function parameter optional.

Believe it or not, I think the formatter wrote these out. I was using `() => {}` as the default value and I guess the formatter didn't like my arg erasure. It's a funny old world

2024-08-30 17:51 UTC, Rezmason commented on packages/editor/src/components/assets/ModelCompressionPanel.tsx
> +
TIL that the TypeScript Record type with an enum key is exhaustive, ie. it throws a useful compiler error if there are any missing enum keys in the declaration ✨

2024-08-30 19:02 UTC, Rezmason commented
> After running a default compression job on a file in "ir-props", the integrated prefab file is getting uploaded into /assets/assets/models rather than /assets/models 

Found to be caused by https://github.com/ir-engine/ir-engine/pull/78

2024-09-05 18:30 UTC, dinomut1 approved these changes

2024-09-05 23:18 UTC, merged