IR-2752 Implement Google Analytics logger
ir-engine/ir-engine pull request #12
Opened 2024-08-19 09:58 UTC by hurairahmateen

## Summary

## Subtasks Checklist

## Breaking Changes

## References
https://tsu.atlassian.net/browse/IR-2752
https://github.com/theinfinitereality/irpro-multitenancy/pull/359

## QA Steps

2024-08-26 19:55 UTC, barankyle approved these changes

2024-08-29 06:11 UTC, hanzlamateen requested changes

2024-08-29 06:11 UTC, hanzlamateen commented on packages/server-core/src/setting/client-setting/client-setting.seed.ts
> +  gaMeasurementId: '',
Can be set through envs.

2024-08-29 06:11 UTC, hanzlamateen commented on packages/server-core/src/setting/client-setting/migrations/20240828064409_gaMeasurementId_column.ts
> +
Can be set through envs if defined

2024-08-29 11:44 UTC, hanzlamateen requested changes

2024-08-29 11:44 UTC, hanzlamateen commented on packages/server-core/src/appconfig.ts
> +  gaMeasurementId: process.env.GOOGLE_ANALYTICS_MEASUREMENT_ID!
Is it required here? Are we using it from config anywhere?

2024-08-30 06:48 UTC, hanzlamateen approved these changes

2024-08-30 06:48 UTC, merged