refactor: Add LoadingView component to Select dropdown
ir-engine/ir-engine pull request #145
Opened 2024-09-03 08:25 UTC by MoizAdnan

https://tsu.atlassian.net/browse/IR-2871

2024-09-03 11:34 UTC, SYBIOTE approved these changes

2024-09-03 12:33 UTC, aditya-mitra requested changes
Adding the `LoadingView` to `Select` makes the loading part tightly coupled.
We can instead pass an `endComponent` prop from `Select` down to `Input` component

2024-09-03 12:33 UTC, aditya-mitra commented on packages/ui/src/primitives/tailwind/Select/index.tsx
> +            <LoadingView spinnerOnly className="mr-2 h-6 w-6" />
`LoadingView` here with a fixed set of props might affect the component's dynamic nature and is tightly coupled. For example, if we need to provide text to the `LoadingView` we will need to add another prop in `SelectProps` which increases prop complexity.

2024-09-04 03:54 UTC, aditya-mitra approved these changes
Looks good ✅

2024-09-04 03:54 UTC, aditya-mitra commented on packages/ui/src/primitives/tailwind/Select/index.tsx
> +          ) : (
one liner 💡

```suggestion
          endComponent ?? (
```

2024-09-04 10:59 UTC, hanzlamateen approved these changes

2024-09-04 10:59 UTC, merged