min max size for thumbnails
ir-engine/ir-engine pull request #225
Opened 2024-09-12 02:58 UTC by SYBIOTE

min max thumbnail size for asset thumbnails

2024-09-13 12:24 UTC, aditya-mitra requested changes, later dismissed
seems to be issues with icon resizing

https://github.com/user-attachments/assets/97160fec-5b83-473b-ad69-4b2e4d0bd9b2

2024-09-18 01:53 UTC, SYBIOTE commented
makes sense, since the minimum is now 80px

2024-09-18 02:32 UTC, SYBIOTE commented
made the necessary adjustments

2024-09-18 18:40 UTC, dinomut1 approved these changes

2024-09-20 02:56 UTC, merged