Michael/ir 4091 video
ir-engine/ir-engine pull request #280
Opened 2024-09-20 00:03 UTC by MbfloydIR

## Summary
https://tsu.atlassian.net/browse/IR-4091
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-09-20 03:27 UTC, HexaField requested changes

2024-09-20 03:27 UTC, HexaField commented on packages/engine/src/scene/components/VideoComponent.tsx
> +  onSet: (entity, component, json) => {
i dont think we need the onset anymore

2024-09-20 03:28 UTC, HexaField submitted a review, later dismissed
this is what the `fit` field should already accomplish. we should avoid making new fields and functions if `fit` is sufficient

2024-09-20 18:06 UTC, MbfloydIR commented on packages/engine/src/scene/components/VideoComponent.tsx
> +  onSet: (entity, component, json) => {
Talked with @MichaelEstes, the onSet is temporarily needed, other wise the video player doesn't work.

2024-09-20 18:07 UTC, MbfloydIR commented
> this is what the `fit` field should already accomplish. we should avoid making new fields and functions if `fit` is sufficient

Removed the letterbox property and made the letterboxing effect always on

2024-09-20 19:54 UTC, MichaelEstes commented on packages/engine/src/scene/components/VideoComponent.tsx
> +  onSet: (entity, component, json) => {
Michael found an issue with component schemas for components that rely on three objects being cloned when set. The onSet can be removed when https://github.com/ir-engine/ir-engine/pull/285 is merged in

2024-09-27 22:03 UTC, MbfloydIR commented on packages/engine/src/scene/components/VideoComponent.tsx
> +  onSet: (entity, component, json) => {
on set has now been removed

2024-10-02 22:06 UTC, Rezmason approved these changes
LGTM!

2024-10-02 22:29 UTC, merged