IR-4575: Magic link email template
ir-engine/ir-engine pull request #311
Opened 2024-09-25 05:52 UTC by jose-galvan

## Summary

Updated the design for the magic link template 

**DESKTOP**

![image](https://github.com/user-attachments/assets/a6b2e1d9-9743-4e71-83ce-54acec74a813)

**Mobile**

![image](https://github.com/user-attachments/assets/1189dd84-4ad4-45f7-84ed-3d7c47ed4595)

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-09-25 20:47 UTC, barankyle approved these changes

2024-09-26 05:16 UTC, hanzlamateen requested changes
Overall, looks great. Just a few minor observations:

1. The font mentioned as 1 in image, is different than result and also differs than the one in figma.
2. The space above and below sign in now button looks different than in designs
3. The space above URL is more than in designs
4. The space between Infinite reality team and welcome text is less than in designs.

![image](https://github.com/user-attachments/assets/c4dd590d-fe49-4357-b8af-03482000eb0e)

2024-09-26 20:15 UTC, jose-galvan commented
> Overall, looks great. Just a few minor observations:
> 
> 1. The font mentioned as 1 in image, is different than result and also differs than the one in figma.
> 2. The space above and below sign in now button looks different than in designs
> 3. The space above URL is more than in designs
> 4. The space between Infinite reality team and welcome text is less than in designs.
> 
> ![image](https://private-user-images.githubusercontent.com/10975502/370993365-c4dd590d-fe49-4357-b8af-03482000eb0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzIwNDAsIm5iZiI6MTcyNzM3MTc0MCwicGF0aCI6Ii8xMDk3NTUwMi8zNzA5OTMzNjUtYzRkZDU5MGQtZmU0OS00MzU3LWI4YWYtMDM0ODIwMDBlYjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE3MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMmIxZjRjZDNhMTYxNjMyMWFlNjVkMTBjMDI5YTE5MjFjNTk4N2Q0MGQ5NzkyYThkM2I0MTE5NTYwZDIzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vjYc6LvVwU-1DF7H7JsHrSSlbnIBYAQAHZ1wS8Hc9VY)

Fixed! Can you give it a look again, please?

2024-10-01 12:34 UTC, hanzlamateen approved these changes

2024-10-01 12:34 UTC, merged