rename skybox from ee_skybox to ir_skybox
ir-engine/ir-engine pull request #339
Opened 2024-09-27 21:22 UTC by MbfloydIR

## Summary
https://tsu.atlassian.net/browse/IR-4782
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-09-29 10:58 UTC, HexaField requested changes
This needs to respect the

2024-09-29 10:58 UTC, HexaField commented on packages/projects/default-project/public/scenes/apartment.gltf
> +      "name": "iR_skybox",
these should all just be `Skybox`

2024-09-30 15:21 UTC, MbfloydIR commented on packages/projects/default-project/public/scenes/apartment.gltf
> +      "name": "iR_skybox",
implemented

2024-09-30 20:41 UTC, HexaField approved these changes

2024-09-30 20:51 UTC, merged