studio: user profile
ir-engine/ir-engine pull request #347
Opened 2024-09-30 19:54 UTC by achen5671

## Summary
https://tsu.atlassian.net/browse/IR-2520
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-10-01 05:53 UTC, aditya-mitra commented
@achen5671 screenshots for these 2
(helps point out the changes faster)

2024-10-04 02:52 UTC, aditya-mitra requested changes, later dismissed
almost done.
can you implement these 3 states that are being shown in the [ir design library figma](https://www.figma.com/design/ln2VDACenFEkjVeHkowxyi/iR-Engine-Design-Library-File?node-id=2839-16186&node-type=frame&t=3utcM0pxpolUGylP-0)?

![image](https://github.com/user-attachments/assets/4523c70e-c186-418c-92a1-e9d3c45ab2fa)

2024-10-04 02:52 UTC, aditya-mitra commented on packages/ui/src/components/tailwind/ContextMenu/index.tsx
revert the change on this file too

2024-10-04 02:52 UTC, aditya-mitra commented on packages/editor/src/components/toolbar/Toolbar.tsx
> +  const profileAnchorEvent = useHookstate<null | React.MouseEvent<HTMLElement>>(null)
can we revert these?
also can you remove the unused variables

2024-10-04 13:21 UTC, achen5671 commented
> almost done. can you implement these 3 states that are being shown in the [ir design library figma](https://www.figma.com/design/ln2VDACenFEkjVeHkowxyi/iR-Engine-Design-Library-File?node-id=2839-16186&node-type=frame&t=3utcM0pxpolUGylP-0)?
> 
> ![image](https://private-user-images.githubusercontent.com/55396651/373480973-4523c70e-c186-418c-92a1-e9d3c45ab2fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDgzNjQsIm5iZiI6MTcyODA0ODA2NCwicGF0aCI6Ii81NTM5NjY1MS8zNzM0ODA5NzMtNDUyM2M3MGUtYzE4Ni00MThjLTkyYTEtZTlkM2M0NWFiMmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDEzMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNTg1ZDYwOGNhNWRkZjE2MDA2NWNhOWFjMjNkZGVjNjUzZTBkMmRkZjgwZDA2Y2ViNWE4NWM3Mzk0M2Q2NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I7LU-1VBoqvs_D0pKwiD-x0fhD5i2pyN-MNospHwyWw)

Im not too sure what the difference is between the default and hover state. Ill add the focus state though

2024-10-04 13:29 UTC, achen5671 commented
> > almost done. can you implement these 3 states that are being shown in the [ir design library figma](https://www.figma.com/design/ln2VDACenFEkjVeHkowxyi/iR-Engine-Design-Library-File?node-id=2839-16186&node-type=frame&t=3utcM0pxpolUGylP-0)?
> > ![image](https://private-user-images.githubusercontent.com/55396651/373480973-4523c70e-c186-418c-92a1-e9d3c45ab2fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNDgzNjQsIm5iZiI6MTcyODA0ODA2NCwicGF0aCI6Ii81NTM5NjY1MS8zNzM0ODA5NzMtNDUyM2M3MGUtYzE4Ni00MThjLTkyYTEtZTlkM2M0NWFiMmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDEzMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNTg1ZDYwOGNhNWRkZjE2MDA2NWNhOWFjMjNkZGVjNjUzZTBkMmRkZjgwZDA2Y2ViNWE4NWM3Mzk0M2Q2NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I7LU-1VBoqvs_D0pKwiD-x0fhD5i2pyN-MNospHwyWw)
> 
> Im not too sure what the difference is between the default and hover state. Ill add the focus state though

![Screenshot 2024-10-04 at 9 29 36 AM](https://github.com/user-attachments/assets/cbc16801-62ae-4421-9763-9e256e7ac6b0)

2024-10-04 20:50 UTC, JT00y approved these changes
looks good, popover modal shows correct

2024-10-07 13:39 UTC, merged