Add more actionTypes & refresh button
ir-engine/ir-engine pull request #38
Opened 2024-08-20 08:32 UTC by CITIZENDOT

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-08-20 08:40 UTC, aditya-mitra requested changes

2024-08-20 08:40 UTC, aditya-mitra commented on packages/client-core/src/admin/components/project/ProjectHistory.tsx
> +          <Text>updated the tags for </Text>
use translation string here

2024-08-20 08:40 UTC, aditya-mitra commented on packages/client-core/src/admin/components/project/ProjectHistory.tsx
> +          <Text>for the resource:</Text>
translation string here

2024-08-20 08:40 UTC, aditya-mitra commented on packages/server-core/src/projects/project-history/migrations/project_triggers.sql
can you tell why the hyphen changed into underscore?

2024-08-21 04:09 UTC, CITIZENDOT commented on packages/server-core/src/projects/project-history/migrations/project_triggers.sql
I wanted to follow this format for filenames for everywhere: `serviceName_triggers.sql`, so that it's easier to search.

2024-08-22 12:47 UTC, CITIZENDOT commented on packages/client-core/src/admin/components/project/ProjectHistory.tsx
> +          <Text>updated the tags for </Text>
Done

2024-08-22 12:47 UTC, CITIZENDOT commented on packages/client-core/src/admin/components/project/ProjectHistory.tsx
> +          <Text>for the resource:</Text>
Done

2024-08-23 02:52 UTC, aditya-mitra approved these changes

2024-08-26 06:45 UTC, hanzlamateen approved these changes

2024-08-26 08:19 UTC, merged