Changing node helpers to be visible by default.
ir-engine/ir-engine pull request #404
Opened 2024-10-10 21:13 UTC by Rezmason

## References
Partially addresses but does not close [IR-4530](https://tsu.atlassian.net/browse/IR-4530).

2024-10-10 21:15 UTC, DanielBelmes approved these changes
great work

2024-10-10 22:38 UTC, DanielBelmes requested changes
I realized right now that this would enable nodeHelperVisibility always. We're going to want to trigger this state to true on editor load. Maybe the same way we do it for grid state.

2024-10-11 00:34 UTC, HexaField commented
We spoke at standup today and have a new approach

2025-01-10 20:29 UTC, SYBIOTE commented
i am going to remove the trigger condition for the helpers from the button and tie it to selection instead

2025-01-10 21:32 UTC, closed without merging

2025-01-10 21:32 UTC, HexaField commented
> i am going to remove the trigger condition for the helpers from the button and tie it to selection instead

We dont need to revive this branch. This was for the wizard.

2025-01-10 23:33 UTC, SYBIOTE commented
Working on a new fresh branch