turn off gizmo for wizard
ir-engine/ir-engine pull request #438
Opened 2024-10-16 20:51 UTC by JT00y

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-10-17 16:46 UTC, aditya-mitra commented on packages/editor/src/systems/EditorControlSystem.ts
> +      urlParams.get('wizardEnabled') === 'false'
`wizardEnabled` comes from the irpro-wizard repo
is there a way we can dynamically do this?
(what if we try to disable it in the irpro-wizard itself by copying some required parts of the EditorControlSystems)

2024-10-17 22:38 UTC, HexaField requested changes
we should not rely on url parameters for this, and we should also not be including any reference to the wizard in the core engine

something that would make more sense is a "gizmoEnabled" boolean in a state that can be turned off from the wizard

2024-10-17 22:55 UTC, JT00y commented
> we should not rely on url parameters for this, and we should also not be including any reference to the wizard in the core engine
> 
> something that would make more sense is a "gizmoEnabled" boolean in a state that can be turned off from the wizard

is it mean I can add a new state for gizmoEnbaled in core engine? where I can put this state?

2024-10-17 23:03 UTC, HexaField commented
> is it mean I can add a new state for gizmoEnbaled in core engine? where I can put this state?

Yes.`EditorHelperState` would make sense

2024-10-18 00:20 UTC, HexaField approved these changes

2024-10-18 17:10 UTC, merged