Save lookdev prefab
ir-engine/ir-engine pull request #525
Opened 2024-10-25 17:53 UTC by JT00y

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-10-25 23:41 UTC, HexaField commented on packages/editor/src/components/dialogs/CreatePrefabPanelDialog.tsx
> +        if (isExportLookDev) {
we definitely need to break this down into smaller functions

2024-10-28 21:14 UTC, dinomut1 requested changes

2024-10-28 21:14 UTC, dinomut1 commented on packages/editor/src/components/dialogs/CreatePrefabPanelDialog.tsx
> +          proxifyParentChildRelationships(obj)
don't need this

2024-10-28 21:14 UTC, dinomut1 commented on packages/editor/src/components/dialogs/CreatePrefabPanelDialog.tsx
> +          })
this is nice. Add a check if lookdevEntity already has this component somewhere.

2024-10-28 21:14 UTC, dinomut1 commented on packages/editor/src/components/dialogs/CreatePrefabPanelDialog.tsx
> +            })
remove this

2024-10-28 21:14 UTC, dinomut1 commented on packages/editor/src/components/dialogs/CreatePrefabPanelDialog.tsx
> +          PopoverState.showPopupover(<PrefabConfirmationPanelDialog entity={entity as Entity} />)
this works, but put it in a helper function that you call at the end of both conditionals

2024-11-04 23:36 UTC, dinomut1 approved these changes
alright!

2024-11-04 23:49 UTC, merged