IR-5050 migrate hem setting to engine setting
ir-engine/ir-engine pull request #570
Opened 2024-10-31 06:36 UTC by mshafiqmk

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-11-07 23:49 UTC, barankyle commented
This needs to be updated off of dev to resolve merge conflicts/

2024-11-13 13:03 UTC, hanzlamateen requested changes

2024-11-13 13:03 UTC, hanzlamateen commented on packages/common/src/schemas/setting/helm-setting.schema.ts
>  export const helmSettingMethods = ['find', 'get', 'create', 'patch', 'remove'] as const
Why this whole schema file is not removed?

2024-11-13 13:03 UTC, hanzlamateen commented on packages/server-core/src/projects/project/project-helper.ts
> +      if (helmSettings.length > 0 && helmBuilder)
```suggestion
      if (helmSettings.length > 0 && helmBuilder && helmBuilder.length > 0)
```

2024-11-13 13:03 UTC, hanzlamateen commented on packages/server-core/src/setting/helm-setting/helm-setting.ts
>  export default (app: Application): void => {
Why is this file not completely removed?

2024-11-13 13:03 UTC, hanzlamateen commented on scripts/fetch-helm-versions.ts
> +      if (helmMain) fs.writeFileSync(helmMainVersionName, helmMain)
Put a length check here too

2024-11-13 13:03 UTC, hanzlamateen commented on scripts/fetch-helm-versions.ts
> +      if (helmBuilder) fs.writeFileSync(helmBuilderVersionName, helmBuilder)
Put a length check here too

2024-11-14 04:40 UTC, mshafiqmk commented on packages/server-core/src/setting/helm-setting/helm-setting.ts
>  export default (app: Application): void => {
this service is getting helm relation information from a helm repo , we need to keep it.

2024-11-14 12:40 UTC, hanzlamateen commented on packages/server-core/src/setting/helm-setting/helm-setting.ts
>  export default (app: Application): void => {
For this you should introduce a new service name `helm-version` and in that service you should introduce the code. The endpoint should have take a query parameter `action` which will have string enum value of `main` or `builder` based on which it should return the helm version.

This service will be somewhat similar to how `packages/server-core/src/integrations/metabase/metabase-url` service is written. As it also makes an external call.

2024-11-14 12:41 UTC, hanzlamateen commented on scripts/fetch-helm-versions.ts
> +      if (helmBuilder) fs.writeFileSync(helmBuilderVersionName, helmBuilder)
@mshafiqmk I think this is not addressed yet

2024-11-14 15:52 UTC, mshafiqmk commented on scripts/fetch-helm-versions.ts
> +      if (helmBuilder) fs.writeFileSync(helmBuilderVersionName, helmBuilder)
you mean on this line ?

``` if (helmBuilder) fs.writeFileSync(helmBuilderVersionName, helmBuilder)```

2024-11-15 12:39 UTC, hanzlamateen commented on scripts/fetch-helm-versions.ts
> +      if (helmBuilder) fs.writeFileSync(helmBuilderVersionName, helmBuilder)
made changes here: https://github.com/ir-engine/ir-engine/pull/570/commits/a5264d89b659fbf55e6afcd5db3f287c92004b09

2024-11-15 12:41 UTC, hanzlamateen commented
Converted to draft untill https://github.com/ir-engine/ir-engine/pull/570/files#r1842155736 is addressed.

2024-11-18 13:08 UTC, hanzlamateen approved these changes

2024-11-18 13:13 UTC, merged