IR-5292 Add asset drag and drop to image link
ir-engine/ir-engine pull request #594
Opened 2024-11-04 22:24 UTC by AidanCaruso

## Summary
Image links don't allow for editing. This PR adds edit/asset drag and drop support.

## Subtasks Checklist

## Breaking Changes

## References
Closes https://tsu.atlassian.net/browse/IR-5292

## QA Steps

2024-11-06 05:16 UTC, aditya-mitra requested changes
Am unsure about file browser support in ImageLink
I have asked the same in [figma](https://www.figma.com/design/ln2VDACenFEkjVeHkowxyi?node-id=2370-20234#1014424457)

I will update this PR depending upon the designs and further resolution.

2024-11-06 05:16 UTC, aditya-mitra commented on packages/ui/src/components/editor/ImageLink/index.tsx
> +  onRelease?: (value: string) => void
we could keep the `onChange` prop name and pass it to FileBrowserInput
`onRelease` is more associated with sliders where we _release_ the input invoking an action

2024-11-12 19:37 UTC, DanielBelmes approved these changes

2024-11-12 20:36 UTC, DanielBelmes requested changes
Was duplicated by https://github.com/ir-engine/ir-engine/pull/610 but that PR is more preferable. Might close this soon

2024-11-13 04:44 UTC, aditya-mitra commented
> Was duplicated by #610 but that PR is more preferable. Might close this soon

Yes Daniel you are right!
Lets close in favour of #610

2024-11-13 04:44 UTC, closed without merging