locked the drag and drop option behind a feature flag
ir-engine/ir-engine pull request #609
Opened 2024-11-05 21:15 UTC by MbfloydIR

## Summary
https://tsu.atlassian.net/browse/IR-5192
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-11-05 23:02 UTC, HexaField requested changes
we don't need a new feature flag for this, we can reuse the point and click flag since the button is a toggle between the two settings, and drag and drop is the default / desirable state

2024-11-05 23:16 UTC, MbfloydIR commented
> we don't need a new feature flag for this, we can reuse the point and click flag since the button is a toggle between the two settings, and drag and drop is the default / desirable state

implemented

2024-11-06 05:00 UTC, aditya-mitra approved these changes
Looks good!

2024-11-06 07:03 UTC, HexaField approved these changes

2024-11-06 07:18 UTC, merged