IR-5260 Envmap of texture changing intensity value removes texture effect on the model
ir-engine/ir-engine pull request #610
Opened 2024-11-05 22:24 UTC by MichaelEstes

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-11-05 22:53 UTC, HexaField requested changes

2024-11-05 22:53 UTC, HexaField commented on packages/ui/src/components/editor/properties/envmap/index.tsx
> -          onRelease={commitProperty(EnvmapComponent, 'envMapIntensity')}
why was the commitProperty removed? how does the value propagate to the authoring layer now?

2024-11-07 02:45 UTC, HexaField commented
Looks good, would like @aditya-mitra 's perspective on the image UI. Maybe due to a merge error?

2024-11-13 04:44 UTC, aditya-mitra commented
> Looks good, would like @aditya-mitra 's perspective on the image UI. Maybe due to a merge error?

Input in images is missing in designs. Have asked the design team to have a look at it.
Related conversation: https://tsu.atlassian.net/browse/IR-5349?focusedCommentId=46101

2024-11-13 21:41 UTC, DanielBelmes approved these changes

2024-11-14 01:25 UTC, HexaField approved these changes

2024-11-14 01:40 UTC, merged