fix offline avatar loading
ir-engine/ir-engine pull request #761
Opened 2024-12-04 09:08 UTC by HexaField

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-12-04 22:08 UTC, AidanCaruso requested changes
The u

2024-12-04 22:08 UTC, AidanCaruso commented on packages/client-core/src/components/World/LoadLocationScene.tsx
> +    const unload = GLTFAssetState.loadScene(resource.url, resource.id)
Changing this to use the resource url includes the hash delimiter which seems to be causing issues with scene loading in my testing

2024-12-04 22:32 UTC, HexaField commented
Urg yeah I think something else is missing. I picked this out of the p2p branch.

2024-12-05 04:01 UTC, HexaField commented
hmm it does seem to be working for me. most examples don't load an avatar, the WebXR ones do.

2024-12-05 05:09 UTC, AidanCaruso approved these changes
Seems fine now

2024-12-05 06:21 UTC, closed without merging