feat(IR-3180): add close button for debug
ir-engine/ir-engine pull request #772
Opened 2024-12-06 04:35 UTC by kattsushi

## Summary
add close button for debug
## Subtasks Checklist

## Breaking Changes

## References
closes [#IR-3180](https://tsu.atlassian.net/browse/IR-3180)
![Screenshot 2024-12-05 at 10 34 04 p m](https://github.com/user-attachments/assets/eb74f4c7-c514-4294-960f-2b8307d0b881)

## QA Steps

2024-12-06 12:30 UTC, aditya-mitra approved these changes
Looks good!

2024-12-06 18:19 UTC, DanielBelmes approved these changes

2024-12-07 00:08 UTC, DanielBelmes requested changes
Can you fix the linting errors please

2024-12-09 20:37 UTC, DanielBelmes approved these changes

2024-12-09 20:51 UTC, merged