IR-6060: Fix Build Failures in npm run local Command
ir-engine/ir-engine pull request #780
Opened 2024-12-06 23:42 UTC by speigg

This PR fixes two issues causing failures in the `npm run local` command:

1. Environment Variables Processing
- Updated Vite's define configuration to properly handle both VITE_ prefixed and other environment variables
- Created separate process.env object in define configuration
- Added specific handling for VITE_ prefixed variables
- Preserved npm_package_bin variables by nesting them under process.env

2. Tailwind CSS Configuration
- Updated content paths to target only relevant source directories:
  - ./packages/client/src/**/*.{ts,tsx}
  - ./packages/ui/src/**/*.{ts,tsx}
  - ./packages/editor/src/**/*.{ts,tsx}
  - ./packages/projects/**/src/**/*.{ts,tsx}
- Prevented build failures from processing non-existent files
- Improved build performance by limiting scope

Testing:
- [x] Verified successful execution of `npm run local`
- [x] Confirmed environment variables are properly accessible
- [x] Verified CSS styles are correctly applied

2024-12-06 23:43 UTC, barankyle approved these changes

2024-12-06 23:44 UTC, HexaField requested changes

2024-12-06 23:44 UTC, HexaField commented on tailwind.config.js
> +    './packages/client/src/**/*.{ts,tsx}',
also need client-core probably? and maybe engine if it has XRUIs

2024-12-07 02:22 UTC, HexaField approved these changes

2024-12-07 02:42 UTC, merged