IR-2872 compress image menu layout fixes
ir-engine/ir-engine pull request #79
Opened 2024-08-26 16:59 UTC by SamMazerIR

menu items were being squished horizontally and taking up two vertical lines, looked bad and didn't match figma, fixing

## Summary
image compression design changes (fix)
menu items were being squished horizontally and taking up two vertical lines, looked bad and didn't match figma, fixing

problem screenshot (from mt-dev/dev):
![current dev/mt-dev](https://github.com/user-attachments/assets/f7b788de-e677-401a-b14c-0115f7995130)

fixed screenshot:
![after my adjustments](https://github.com/user-attachments/assets/8acfb7db-0e4e-4bc1-abf7-f5f96cad504f)

## References
[https://tsu.atlassian.net/browse/IR-2872](https://tsu.atlassian.net/browse/IR-2872)

[figma reference](https://www.figma.com/design/DXwFHGa5g0peqqSjyjpxQz/Studio-Design?node-id=6149-9649&t=D3reKkRs0GeFUqVl-0)

figma screenshot:
![figma screencap](https://github.com/user-attachments/assets/74e17b04-af32-402d-a286-3c1363072dc0)

## QA Steps
go to files tab and select an image, right click it and select "compress" to bring up menu

2024-08-26 17:06 UTC, aditya-mitra requested changes, later dismissed
can you also check if it retains this width on smaller and larger screens?

2024-08-26 17:06 UTC, aditya-mitra commented on packages/editor/src/components/assets/ImageCompressionPanel.tsx
> +      <div className="mx-auto grid w-[80%] justify-center gap-y-2">
```suggestion
      <div className="mx-auto grid w-4/5 justify-center gap-y-2">
```

2024-08-26 18:47 UTC, SamMazerIR commented
> can you also check if it retains this width on smaller and larger screens?

the popup is set to a fixed 680px wide (not my change)

2024-08-27 07:20 UTC, aditya-mitra approved these changes
awesome 🚀

2024-08-27 07:43 UTC, merged