changed the order of execution to get the highlight effect to work again
ir-engine/ir-engine pull request #831
Opened 2024-12-12 20:06 UTC by MbfloydIR

## Summary
https://tsu.atlassian.net/browse/IR-6062
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-12-12 21:06 UTC, HexaField requested changes
Whilst this may fix the issue, we need to make sure the useEffect has the correct dependencies. Let's add `!!rendererComponent.effectComposer.value` as a dependency of the useEffect for the highlight effect, and ensure that it exists. Without this, it could still break (possibly in tests)

2024-12-17 05:57 UTC, HexaField requested changes, later dismissed
I'm not seeing the highlight effect in the studio still

2025-01-14 02:31 UTC, DanielBelmes commented
I did changes to make the useEffects work as initially expected but the reorder still saves some extranous useeffect runs. It's minuscule but an improvements an improvement. @HexaField

2025-01-14 03:54 UTC, DanielBelmes commented
tests fixed

2025-01-14 03:54 UTC, DanielBelmes commented
test might be fixed. Didn't test locally because it's 8pm but fingers crossed.

2025-01-15 18:38 UTC, SamMazerIR approved these changes

2025-01-15 22:42 UTC, merged