[IR-5703] Unit Test - Spatial XR coverage: Component & System Reactors
ir-engine/ir-engine pull request #845
Opened 2024-12-14 02:18 UTC by heysokam

## Summary

## Subtasks Checklist

## Breaking Changes

## References
https://tsu.atlassian.net/browse/IR-5703

## QA Steps

2024-12-17 07:29 UTC, HexaField requested changes

2024-12-17 07:29 UTC, HexaField commented on packages/spatial/src/xr/XRDepthOcclusion.tsx
> +    return () => {
we still need a session active check here, otherwise this will run when a session is made active too

2024-12-17 22:26 UTC, heysokam commented on packages/spatial/src/xr/XRDepthOcclusion.tsx
> +    return () => {
Oh, good catch! I was meaning to revert this yesterday after asking you guys about it, but totally forgot.
Fixed with 640ac97

2025-03-18 09:20 UTC, HexaField approved these changes

2025-03-18 09:31 UTC, merged