Add description field to file properties modal
ir-engine/ir-engine pull request #94
Opened 2024-08-27 19:15 UTC by dinomut1

Adds text area field for editing a file's description

2024-08-29 17:16 UTC, Rezmason commented on packages/ui/src/primitives/tailwind/TextArea/index.tsx
> +    )
Is this preferable to `flex w-full flex-col items-center ${containerVariants[variant] ${containerClassName}`? What's the difference?

2024-08-29 17:20 UTC, Rezmason approved these changes

2024-08-30 04:16 UTC, aditya-mitra commented on packages/ui/src/primitives/tailwind/TextArea/index.tsx
have asked Yulia for a textarea input design.
it it best to use a design system currently.

2024-08-30 04:17 UTC, aditya-mitra requested changes
waiting for text area input
(I will add the text area design in this PR itself)

2024-09-06 21:17 UTC, dinomut1 commented
We need this to proceed with using this field for wizard development. We can swap this design out for whatever Yulia decides upon later, but for now i'm going to go ahead and merge this in

2024-09-06 21:26 UTC, merged